apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: genesio-vs
spec:
  hosts:
    - "*"
  gateways:
    - genesio-gateway
  http:
  - match:
    - headers:
        version:
          exact: v2
    route:
    - destination:
        host: genesio
        subset: v2
  - route:
    - destination:
        host: genesio
        subset: v1
        port:
          number: 8080
